### ISSUE TITLE
用这个越狱方法是不是就可以把不需要的启动项关闭？

### ISSUE THREAD

**Issue by tiger-art** [fankes/HanvonEBookHacker#1]
你好，我手上的汉王F30II二代，用这个越狱方法是不是就可以把不需要的启动项关闭（比如音频，之类的。只保留一个看书功能在后台）？现在太费电了，现在是5天一充，新电池。想省电

**Comment by fankes** [comment]
`ebook.exe` 这玩意是一体的，没法单独停用某些功能

**Comment by tiger-art** [comment]
哦。封闭系统，跟苹果手机越狱一样，只能增加额外功能，无法停止原机器的功能。

**Comment by fankes** [comment]
毕竟定制化的设备，程序不可能开源，没有源码什么都做不了，wince 这玩意早就被微软淘汰了，它要是个安卓还好办，这么老的机子了没什么折腾的必要了，不需要额外的功能就建议凑合用吧

**Comment by tiger-art** [comment]
谢谢回复。打算卖掉，换一个。续航太差劲了。-_-
